### ISSUE TITLE
Error when trying to move content

### ISSUE THREAD

**Issue by ilocit** [cuzy-app/humhub-modules-move-content#3]
I have some content on Humhub v 1.15 created by the original "Admin" of the site/installation.

My goal is to move this content to a new user which I created. When starting the "move", I always get this same not very helpful error:

![image](https://github.com/cuzy-app/humhub-modules-move-content/assets/26718215/789affd0-8170-43b4-8640-9bc6fc19d4a9)

"_Uuuups ... Du hast womöglich den falschen Weg eingeschlagen.
Es ist ein interner Fehler aufgetreten_."

(ENG: Uuuups ... You maybe took the wrong way.
An internal error occured.)

Any idea what is wrong?

Thanks!

**Comment by marc-farre** [comment]
@ilocit thanks for reporting the issue!
Fixed in release 1.1.1 which should soon be available on the Marketplace.

**Comment by ilocit** [comment]
Excellent. Works now. Thanks for the quick fix, @marc-farre !
